# Changes here will be overwritten by Copier
_commit: v7.2.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-ssh
project_description: Get files and process output via secure shell protocol.
project_slug: ssh
project_type: plugin
pypi: true

